services:
  mysql:
    ports:
      - "3306:3306"

  app:
    image: nazmulpcc/registry:develop
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  caddy:
    volumes:
      - ~/.caddy/authorities:/data/caddy/pki/authorities

