services:
    app:
        restart: unless-stopped
        image: nazmulpcc/registry:latest
        env_file:
            - ./.env
        volumes:
            - ./storage:/app/storage
        depends_on:
            - mysql

    caddy:
        restart: unless-stopped
        image: caddy:2.10-alpine
        environment:
            - CERTIFICATE_MODE=${CERTIFICATE_MODE}
            - APP_DOMAIN=${APP_DOMAIN}
        depends_on:
            - app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy:/data
            - .:/app

    registry:
        restart: unless-stopped
        image: registry:3.0
        depends_on:
            - redis
        volumes:
            - registry:/var/lib/registry
            - ./registry.yml:/etc/distribution/config.yml
        environment:
            - REGISTRY_HTTP_SECRET=${REGISTRY_HTTP_SECRET}

    mysql:
        restart: unless-stopped
        image: mariadb:lts-noble
        #    command: --default-authentication-plugin=mysql_native_password
        environment:
            - MARIADB_DATABASE=${DB_DATABASE}
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql

    redis:
        image: redis:alpine

volumes:
    caddy:
    mysql:
    registry:
